# Generated by Django 5.1.2 on 2024-12-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioSaving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blob_url",
                    models.FileField(blank=True, null=True, upload_to="audio_files/"),
                ),
                ("is_transcribed", models.BooleanField(default=False)),
                ("is_extracted", models.BooleanField(default=False)),
                ("transcription_text", models.TextField(blank=True, null=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
