# Generated by Django 5.1.2 on 2024-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_audiosaving_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosaving",
            name="audio_file",
            field=models.FileField(upload_to="audio_files/"),
        ),
    ]
