# Generated by Django 5.1.2 on 2024-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_audiosaving_audio_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiosaving",
            old_name="audio_file",
            new_name="blob_url",
        ),
        migrations.AddField(
            model_name="audiosaving",
            name="audio_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="audiosaving",
            name="file_blog_uri",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="audiosaving",
            name="is_transcribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="audiosaving",
            name="transcription_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
