# Generated by Django 5.1.2 on 2024-12-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_audio_file_audiosaving_blob_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosaving",
            name="base_64_string",
            field=models.TextField(blank=True, null=True),
        ),
    ]
