# Generated by Django 5.1.2 on 2024-12-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_audiosaving_base_64_string"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiosaving",
            name="audio_file_name",
        ),
        migrations.RemoveField(
            model_name="audiosaving",
            name="base_64_string",
        ),
        migrations.RemoveField(
            model_name="audiosaving",
            name="file_blog_uri",
        ),
        migrations.AlterField(
            model_name="audiosaving",
            name="blob_url",
            field=models.FileField(blank=True, null=True, upload_to="audio_files/"),
        ),
    ]
