# Generated by Django 5.1.2 on 2024-12-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GmailAccountDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(default="example@gmail.com", max_length=254),
                ),
                ("total_messages", models.IntegerField(default=1000)),
                ("total_threads", models.IntegerField(default=1000)),
            ],
        ),
    ]
